---
fixtures:
  repositories:
    apache:     "git://github.com/simp/pupmod-simp-apache"
    auditd:     "git://github.com/simp/pupmod-simp-auditd"
    augeasproviders:             "git://github.com/simp/augeasproviders"
    augeasproviders_base:        "git://github.com/simp/augeasproviders_base"
    augeasproviders_core:        "git://github.com/simp/augeasproviders_core"
    augeasproviders_grub:        "git://github.com/simp/augeasproviders_grub"
    augeasproviders_puppet:      "git://github.com/simp/augeasproviders_puppet"
    augeasproviders_apache:      "git://github.com/simp/augeasproviders_apache"
    augeasproviders_mounttab:    "git://github.com/simp/augeasproviders_mounttab"
    augeasproviders_nagios:      "git://github.com/simp/augeasproviders_nagios"
    augeasproviders_pam:         "git://github.com/simp/augeasproviders_pam"
    augeasproviders_postgresql:  "git://github.com/simp/augeasproviders_postgresql"
    augeasproviders_shellvar:    "git://github.com/simp/augeasproviders_shellvar"
    augeasproviders_ssh:         "git://github.com/simp/augeasproviders_ssh"
    augeasproviders_sysctl:      "git://github.com/simp/augeasproviders_sysctl"
    #augeasproviders_syslog:    "git://github.com/simp/augeasproviders_syslog"
    concat:     "https://github.com/puppetlabs/puppetlabs-concat.git"
    inifile:    "git://github.com/simp/puppetlabs-inifile"
    iptables:   "git://github.com/simp/pupmod-simp-iptables"
    logrotate:  "git://github.com/simp/pupmod-simp-logrotate"
    pki:        "git://github.com/simp/pupmod-simp-pki"
    pam:        "git://github.com/simp/pupmod-simp-pam"
    pupmod:     "git://github.com/simp/pupmod-simp-pupmod"
    postgresql:
      repo:   "git://github.com/simp/puppetlabs-postgresql"
      branch: 'simp-master'
    oddjob:     "git://github.com/simp/pupmod-simp-oddjob"
    openldap:   "git://github.com/simp/pupmod-simp-openldap"
    rsync:      "git://github.com/simp/pupmod-simp-rsync"
    rsyslog:    "git://github.com/simp/pupmod-simp-rsyslog"
    simp:       "git://github.com/simp/pupmod-simp-simp"
    simplib:    "git://github.com/simp/pupmod-simp-simplib"
    simpcat:    "git://github.com/simp/pupmod-simp-concat"
    sssd:       "git://github.com/simp/pupmod-simp-sssd"
    stdlib:     "git://github.com/simp/puppetlabs-stdlib"
    tcpwrappers: "git://github.com/simp/pupmod-simp-tcpwrappers"
  symlinks:
    foreman: "#{source_dir}"
