require 'spec_helper_acceptance'

test_name 'foreman class'

describe 'foreman class' do
  let(:client){ only_host_with_role( hosts, 'client' ) }
  let(:server){ only_host_with_role( hosts, 'server' ) }
  let(:client_fqdn){ fact_on( client, 'fqdn' ) }
  let(:server_fqdn){ fact_on( server, 'fqdn' ) }

#  let(:manifest) {
#    <<-EOS
#      class { 'foreman':
#        admin_password: 'password',
#      }
#
#      class { 'foreman::proxy::trusted_hosts':
#        [#{server}],
#      }
#    EOS
#  }


  ### LDAP passwords: 123$%^qweRTY
  let(:server_default_hieradata) {
      <<-EOS
# Obviously include all other necessary classes for this host. This is only to show
# some sample site data you may wish to have. If the default configuration works for you,
# then this won't be needed.
classes:
  - foreman
  - site::foreman
  - simp::ldap_server
  - tcpwrappers
  - pam
  - pam::access


# By default, the admin user password will be autogenerated and nonsensical looking.
# Set that here if you wish to have control over it.
foreman::admin_password : 'No one will never hack this!'

# These are the hosts that will connect to your Foreman proxy. You'll want to make sure
# all hosts who are reporting to Foreman appear here.
foreman::proxy::trusted_hosts :
  - #{server_fqdn}
  - #{client_fqdn}

# Make sure reporting is turned on in Puppet!
pupmod::report : true

#
# ------------------------------------------------------------------------------
# extra hieradata needed to configure dependencies
client_nets: ['ALL']
use_iptables: true
"::use_sssd": false
apache::rsync_web_root: false
rsync::server: 127.0.0.1

# ------------------------------------------------------------------------------

# === use_ldap ===
# Whether or not to use LDAP on this system.
# If you disable this, modules will not attempt to use LDAP where possible.
use_ldap: true

# === ldap::base_dn ===
# The Base DN of the LDAP server
"ldap::base_dn": "dc=fakedomain"

# === ldap::bind_dn ===
# LDAP Bind Distinguished Name
"ldap::bind_dn": "cn=hostAuth,ou=Hosts,%{hiera('ldap::base_dn')}"

# === ldap::bind_pw ===
# The LDAP bind password
"ldap::bind_pw": "123$%^qweRTY"

# === ldap::bind_hash ===
# The salted LDAP bind password hash
"ldap::bind_hash": "{SSHA}Tva27L86sfTyLS059Es0S4lsHEzvevIH"

# === ldap::sync_dn ===
#
"ldap::sync_dn": "cn=LDAPSync,ou=Hosts,%{hiera('ldap::base_dn')}"

# === ldap::sync_pw ===
# The LDAP sync password
"ldap::sync_pw": "123$%^qweRTY"

# === ldap::sync_hash ===
#
"ldap::sync_hash": "{SSHA}xr8JTXnSdOlqFJfP6tNwDNmGfGKKhdbr"

# === ldap::root_dn ===
# The LDAP root DN.
"ldap::root_dn": "cn=LDAPAdmin,ou=People,%{hiera('ldap::base_dn')}"

# === ldap::root_hash ===
# The LDAP root password hash.
#  If you set this with simp config, type the password and the hash will be
# generated for you.'
"ldap::root_hash": "{SSHA}cbyG41/oc3qhJkUpkrjqz60ZUizBxTHJ"

# === ldap::master ===
# This is the LDAP master in URI form (ldap://server)
"ldap::master": "ldap://#{server_fqdn}"

# === ldap::uri ===
# List of OpenLDAP servers in URI form (ldap://server)
"ldap::uri":
  - "ldap://#{server_fqdn}"

EOS
  }


  let(:server_manifest) {
    <<-EOS
      hiera_include('classes')

      # SCLs must be configured first
      # NOTE: This might be 'centos-release-SCL' in EL6
      package{'centos-release-scl': ensure => 'present', }


      yumrepo{ 'bintray':
         ensure  => 'present',
         enabled => true,
         baseurl => 'https://dl.bintray.com/simp/5.1.X',
         gpgkey  => 'https://raw.githubusercontent.com/NationalSecurityAgency/SIMP/master/GPGKEYS/RPM-GPG-KEY-SIMP',
      }
      ->
      Package['simp-ppolicy-check-password']

      yumrepo{ 'foreman':
         ensure  => 'present',
         enabled => true,
         baseurl => 'http://yum.theforeman.org/releases/latest/el7/x86_64/',
         gpgkey  => 'http://yum.theforeman.org/releases/latest/RPM-GPG-KEY-foreman',
         before  => Class['foreman'],
      }

      ::pam::access::manage { "Allow 'vagrant'":
          users   => 'vagrant',
          origins => ['ALL']
      }

      ::tcpwrappers::allow{ 'sshd':
        pattern => 'ALL',
      }

      ::iptables::add_tcp_stateful_listen{ 'allow_sshd':
              client_nets => ['any'],
              dports      => ['22'],
      }

      class site::foreman {
        # Adds an LDAP authentication source to Foreman. This assumes this authentication source
        # is LDAP and already exists. By default, this define will
        foreman::auth_source { '#{server_fqdn}':
          server => $::fqdn,
        }

        foreman::user { 'amazing.user':
          auth_source => 'Internal', # '#{server_fqdn}',
          web_admin   => true,
          firstname   => 'Amazing',
          lastname    => 'User',
        }

        foreman::user { 'untrustworth.user':
          auth_source => 'Internal', # '#{server_fqdn}',
          web_admin   => false,      # This is the default, but want to show the difference from above.
          firstname   => 'Untrustworthy',
          lastname    => 'User',
        }
      }
    EOS
  }


  context 'default parameters' do
    # Using puppet_apply as a helper
    it 'should work with no errors' do
      set_hieradata_on( server, server_default_hieradata, 'default' )
      apply_manifest_on(server, server_manifest, :catch_failures => true)
    end

    it 'should be idempotent' do
      apply_manifest_on(server, server_manifest, :catch_changes => true)
    end


    describe package('foreman') do
      it { is_expected.to be_installed }
    end

    describe service('foreman') do
      it { is_expected.to be_enabled }
      it { is_expected.to be_running }
    end
  end
end
